### ISSUE TITLE
US - Create Task Page

### ISSUE THREAD

**Issue by nastiche** [nastiche/taskifai#1]
## Value Proposition

**As a** user

**I want to be able to** enter a task

**so that I can** store it and get back to it any time later.
​

## Description

![us1_final](https://github.com/nastiche/taskifai/assets/97537490/bd7ecfb1-fb49-4eb6-8b1f-8395b6f62664)

## Acceptance Criteria

- [ ] The header is displayed
- [ ] The input field Title is displayed, accepts text value, focuses on click
- [ ] The input field Subtasks is displayed, accepts text value, focuses on click
- [ ] The input field Category is displayed, accepts text value, focuses on click
- [ ] The input field Deadline is displayed, accepts text value, focuses on click
- [ ] The input field Prioritisation is displayed, accepts check value, focuses on click
- [ ] The button Add is displayed
- [ ] Clicking Add button shows the created task in the tasks list under the task input form
- [ ] The button Reset is displayed
- [ ] Clicking the Reset button resets the input form
      ​

## Tasks

- [ ] Create branch `task-input-form`
- [ ] Create component `Header`
- [ ] Create component `Layout` that renders the `Header` component
- [ ] Create component `TaskInputForm`
- [ ] Create component `TasksList`
- [ ] `TasksList` props: `tasks`
- [ ] Create component `TaskPreviewCard`
- [ ] `TaskPreviewCard` props: `title`, `deadline`, `category`, `prioritisation`
- [ ] Write function for Add button
- [ ] Write function for Reset button

**Comment by actyvystom** [comment]
A nice first one!
Please consider the following comments:
- Your **title** is a bit odd, why do you set these underscores? Please keep it simple and readable 🙂 

Your **value proposition** talks of an efficient person, sounds somehow exclusive and is not a classical role for a user story. Please stick to common roles like `user`. If you want to emphasize efficiency, better cover it in the goal of your user story, e.g. 
> As a user
> I want to be able to enter a task 
> so that I can store it and track keep it efficiently

- Also mind the spelling: you are talking of all todos but your form is designed to set them up one by one. 

Regarding your **acceptance criteria**

Try getting even more detailed, e.g. the input field `xy` is displayed and accepts text value, focuses on click etc. 

Concerning **Task list**: 
- List the tasks explicitly (it does not make sense to create references via 📋 to the Acceptance criteria)

Finally: Please wait for the review before editing the user story 🙂

**Comment by actyvystom** [comment]
A nice rework, almost getting there 🙂
Just a tiny remark:
- Although might seem obvious to you, you should add the creating a branch to your task list (just as a reminder for yourself)
