### ISSUE TITLE
US - Create Task (AI Mode)

### ISSUE THREAD

**Issue by nastiche** [nastiche/taskifai#12]
## Value Proposition

**As a** user

**I want to be able to** switch to AI-mode 

**so that I can** enter just one piece of text and let AI crate task details for me.
​

## Description

![us6](https://github.com/nastiche/taskifai/assets/97537490/e7c02767-621e-483a-8aa7-ef895cf4cb58)

## Acceptance Criteria

- [ ] On the CreateTaskPage the toggle switch with `manual` text on the left and `AI` text on the right is displayed
- [ ] Toggling between `manual` and `AI` mode is possible
- [ ] In `manual` mode input fields from the [US - Create Task Page (Create R U D)](https://github.com/nastiche/taskifai/issues/1) are displayed
- [ ] In `AI` mode `task description` field is displayed
- [ ] On the `TaskDetailsPage` `original task text` field title with an arrow next to it is displayed
- [ ] Clicking on the arrow next to the `original task text` field displays original task text

## Tasks

- [ ] Create branch `ai-mode`
- [ ] Create toggle switch `ModeToggleSwitch`
- [ ] Write function for `ModeToggleSwitch`
- [ ] Edit component `TaskInputForm` to adapt it to two modes
- [ ] Create `OriginalTaskTextToggle` component
- [ ] Add `original task text` field to the `TaskDetails` component
- [ ] Add `OriginalTaskTextToggle` button to the `TaskDetails` component

**Comment by MariaRiosNavarro** [comment]
In my humble opinion I think you have explained well what you want to do. and the acceptance and task criteria are very detailed. great job 🚀
