### ISSUE TITLE
US - Info Pop-ups

### ISSUE THREAD

**Issue by nastiche** [nastiche/taskifai#13]
## Value Proposition

**As a** user

**I want to be able to** see that my actions in the app were successful 

**so that I can** be sure that I don't loose any important input.
​

## Description

![us7](https://github.com/nastiche/taskifai/assets/97537490/75f04ee4-c980-4a90-86d5-a84b49dd391f)

## Acceptance Criteria

- [ ] After click on `create` button on the `CreateTaskPage` `task created` pop-up appears for a few seconds
- [ ] After click on `save` button on the `TaskEditPage` `task saved` pop-up appears for a few seconds
- [ ] After click on `delete` button on the `TaskEditPage` user is redirected to the `TasksListPage` ([US - Task Delete Button (C R U Delete)](https://github.com/nastiche/taskifai/issues/5)) where `task deleted` pop-up appears for a few seconds

## Tasks

- [ ] Create `PopUpBanner` component
- [ ] Implement pop-up function in `create`, `save` and `delete` buttons' handlers

**Comment by CarstenJahnke** [comment]
LGTM 😊🎉
