### ISSUE TITLE
US - Tasks Search

### ISSUE THREAD

**Issue by nastiche** [nastiche/taskifai#15]
## Value Proposition

**As a** user

**I want to be able to** search my tasks in the tasks list

**so that I can** have a better overview of what needs to be done.
​

## Description

![us9](https://github.com/nastiche/taskifai/assets/97537490/dc1cbc61-6630-4a8d-9596-54b7403ec309)

## Acceptance Criteria

- [ ] On the `TasksListPage` input field `search` is displayed
- [ ] Typing tag text in the `search` field displays only tasks in the list which have this tag 

## Tasks

- [ ] Create `SearchBar` component
- [ ] Implement `SearchBar` component in the `TasksListPage`

**Comment by CarstenJahnke** [comment]
👍🎉
