### ISSUE TITLE
US - Tasks List Page

### ISSUE THREAD

**Issue by nastiche** [nastiche/taskifai#2]
## Value Proposition

**As a** user

**I want to** see a list of all my tasks

**so that** I can plan my time accordingly.
​

## Description

![us2_final](https://github.com/nastiche/taskifai/assets/97537490/988e9001-d137-4449-9e6c-a23b35cdfc87)

​

## Acceptance Criteria

- [ ] A navigation link labeled "Create Task" is displayed
- [ ] A navigation link labeled "Tasks List" is displayed
- [ ] Clicking "Create Task" shows CreateTaskPage
- [ ] Clicking "Tasks List" shows TasksListPage
      ​

## Tasks

- [ ] Create branch `tasks-list`
- [ ] Adapt the page `pages/index`: rename the function to `TasksListPage` and have it render only the `TasksList` component
- [ ] Create the page `pages/create-task/index` that renders the `TaskInputForm` component
- [ ] Create the component `Navigation` that renders all navigation links
- [ ] Let the the `Layout` component render the `Navigation` component

**Comment by sebastianwel** [comment]
Hey Nasti, so far so good from my side. One question I have is about the clicking of the buttons at the bottom. Did you already implemented the "CreateTaskPage" and "TaskListPage" at this point?

**Comment by nastiche** [comment]
Hi Sebastian, I created components TaskInputForm and TasksList in the US1 and in the US2 I split those two components on two pages, like we did in the recap Project Quiz App
