### ISSUE TITLE
Task Details Page

### ISSUE THREAD

**Issue by nastiche** [nastiche/taskifai#3]
## Value Proposition

**As an** efficient person

**I want to** be able to see all details of a task

**so that** I can plan it's execution precisely.
​

## Description

![Pasted image 20230614184031](https://github.com/nastiche/taskifai/assets/97537490/1a847eb1-e239-46a5-b42a-8ca86414d14e)

## Acceptance Criteria

- [ ] The disabled input field for the task title is displayed 📋
- [ ] The disabled input field for the initial note text is displayed 📋
- [ ] The disabled input field for the list of sub-tasks is displayed 📋
- [ ] The disabled input field for the task category is displayed 📋
- [ ] The disabled input field for  the task deadline is displayed 📋
- [ ] The disabled input field for the task prioritisation is displayed 📋
- [ ] The edit button is displayed 📋 
- [ ] The delete button is displayed 📋​

## Tasks

- [ ] Write the component TaskEditForm
- [ ] TaskEditForm props: `title`, `subtasks`, `category`, `deadline`, `prioritisation`
- [ ] All acceptance criteria marked with 📋 are covered by component testing

**Comment by sebastianwel** [comment]
I assume, that the functionalities of the nav bar are working here accordingly as in the previous ticket, right?

**Comment by sebastianwel** [comment]
Looks good to me!
