### ISSUE TITLE
US - Edit Task Page (C R Update D)

### ISSUE THREAD

**Issue by nastiche** [nastiche/taskifai#4]
## Value Proposition

**As a** user

**I want to** be able to edit all details of a task

**so that** I can adapt to changes in my plans.
​

## Description

![us4_final](https://github.com/nastiche/taskifai/assets/97537490/a7fcde86-79c7-46b6-aff5-9ac2777535e4)

​
## Acceptance Criteria

- [ ] The input form with task's details as default values is displayed, input fields are disabled
- [ ] The Edit button is displayed
- [ ] Clicking the Edit button changes it to Save button and enables the input fields of the input form
- [ ] Clicking the Save button changes it to Edit button
      ​

## Tasks

- [ ] Create branch `task-edit`
- [ ] Write function for `Edit` button
- [ ] Write function for `Save` button

**Comment by ThysBat** [comment]
So overall a nice userstory! There are just a few things I'd like to mention.

I struggle with the task "Change `back` button to `edit` button" since I would just change the text. Maybe you want to clarify on what event the button shall change?
What is also not clear to me is if the save button actually saves the new input values or not? Because in your tasks you want to write a save button function but it is not part of the acceptance criteria.

**Comment by nastiche** [comment]
There is no event, I just throw the Back button out and replace it with Edit button. I had to add Back button to the form in the previous user story, because my input form component has a button and it should have a function. Otherwise I couldn't have used the input form component in the previous story
