### ISSUE TITLE
US - Task Delete Button (C R U Delete)

### ISSUE THREAD

**Issue by nastiche** [nastiche/taskifai#5]
## Value Proposition

**As an** efficient person

**I want to** be able to delete a task

**so that** I can keep my tasks list up to date.
​

## Description

![us5_final](https://github.com/nastiche/taskifai/assets/97537490/e449a263-c8ff-4959-8576-29f468e34bb3)

## Acceptance Criteria

- [ ] The Delete button is displayed
- [ ] Clicking the Delete button deletes the task and switches the view to the tasks list page
      ​

## Tasks

- [ ] Create branch `task-delete`
- [ ] Create `Delete` button
- [ ] Write function for `Delete` button

**Comment by sebastianwel** [comment]
LGTM! However I would just add a tiny thing to the acceptance criteria, even though you already mentioned it in the value proposition:
- [ ] clicking the delete button, deletes the task from the tasks list

Since it is mandatory for your function.

**Comment by nastiche** [comment]
I know what you mean. I didnt want to mention the tasks list, because the user doesn't actually see it on the details page. I decided to write:  "Clicking the Delete button deletes the task and brings us back to the tasks list page"

**Comment by sebastianwel** [comment]
yes, I think most important was to add that the task will be deleted
