### ISSUE TITLE
US6 - Reset Task Input Form

### ISSUE THREAD

**Issue by nastiche** [nastiche/taskifai#6]
## Value Proposition

**As a** user

**I want to be able to** reset the task input form

**so that I can** start entering the task from the very beginning if I changed my mind during the input process.
​

## Description

![us1_final](https://github.com/nastiche/taskifai/assets/97537490/da11556e-dbb1-4be8-a6b4-b36552b908d7)

## Acceptance Criteria

- [ ]  The Reset button is displayed
- [ ]  Clicking the Reset button resets the input form

      ​

## Tasks

- [ ] Create branch `reset-task-input-form`
- [ ] Write function for Reset button
